import { openai, supabase } from './config.js';

// User query about podcasts
const query = "Training puppies";
main(query);

/*
  Create an embedding from the user input and return a 
  semantically matching text chunk from the database 
*/
async function main(input) {
  // Create a vector embedding representing the input text
  const embeddingResponse = await openai.embeddings.create({
    model: "text-embedding-ada-002",
    input,
  }); 
  
  // The vector generated by OpenAI
  const embedding = embeddingResponse.data[0].embedding;
  
  // Query Supabase for nearest vector match
  const { data } = await supabase.rpc('match_documents', {
    query_embedding: embedding,
    match_threshold: 0.50,
    match_count: 1
  });
  console.log(data[0].content, data[0].similarity);
}
